name: puzzle-two

dependencies:
- base
- containers
- extra
- sbv

executable:
  source-dirs: src
  main: Main.hs

language: GHC2021

default-extensions:
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- ImportQualifiedPost
- LambdaCase
- UnicodeSyntax
