name: puzzle-two

dependencies:
- base
- containers
- extra
- iso-deriving
- sbv

library:
  source-dirs: src

executable:
  source-dirs: main
  main: Main.hs
  dependencies:
  - puzzle-two

language: GHC2021

default-extensions:
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- DerivingVia
- BlockArguments
- ImportQualifiedPost
- LambdaCase
- UnicodeSyntax
