name: puzzle-two

dependencies:
- base
- containers
- extra
# - iso-deriving
- sbv

library:
  source-dirs: src

executable:
  source-dirs: main
  main: Main.hs
  dependencies:
  - puzzle-two

language: GHC2021

default-extensions:
- BlockArguments
- ImportQualifiedPost
- LambdaCase
- UnicodeSyntax
# For Generic
- DeriveAnyClass
# - DeriveFoldable
# - DeriveFunctor
# - DeriveTraversable
# - DerivingVia
