name: puzzle-two

dependencies:
- base
- sbv

library:
  source-dirs: src

executable:
  source-dirs: main
  main: Main.hs
  dependencies:
  - puzzle-two

language: GHC2021

default-extensions:
- LambdaCase
- UnicodeSyntax
